In [350]:
data = []
with open("data/input_4.txt", "r") as file:
    for line in file:
        line = line.strip()
        data.append(line)
display(data[:10], len(data))

draws = data[0].split(",")
draws = [int(i) for i in draws]
setOfTables = data[1:]

['26,38,2,15,36,8,12,46,88,72,32,35,64,19,5,66,20,52,74,3,59,94,45,56,0,6,67,24,97,50,92,93,84,65,71,90,96,21,87,75,58,82,14,53,95,27,49,69,16,89,37,13,1,81,60,79,51,18,48,33,42,63,39,34,62,55,47,54,23,83,77,9,70,68,85,86,91,41,4,61,78,31,22,76,40,17,30,98,44,25,80,73,11,28,7,99,29,57,43,10',
 '',
 '57 12 60 96 93',
 '73 87 63 70 91',
 '74 32 43 67 46',
 '59 34  5 35 82',
 '53 40 55 29  1',
 '',
 '48 71 59 45 63',
 '13 42 23 95 39']

601

In [342]:
import numpy as np

# save tables as matrices
tables = []
matrix = []
for row in setOfTables:
    if row == '':
        if matrix != []: # except the first one
            # write previous
            matrix = np.matrix(matrix)
            tables.append(matrix)
            matrix = []
    else:
        matrix.append([int(i) for i in row.split()])

tables_to_cross_out = tables
first_table_data = []
for numberDrawn in draws:
    for table in tables_to_cross_out:
        # if the number is in the table, replace the number with -1 (mark it as crossed out)
        if numberDrawn in table:
            table[table == numberDrawn] = -1
            # check for BINGO (is there a column or a row which has all values equal to "-1"?)
            if (table == -1).all(axis=0).any() or (table == -1).all(axis=1).any():
                first_table_data.append([table, numberDrawn])
    if first_table_data != []:
        break
firstTable, decidingNumber = first_table_data[0]

print(f"The first table to win is \n\n{firstTable}\n\nand the deciding number was {decidingNumber}\n")
print(f"Sum of the whole table including -1 is {firstTable.sum()}")

# Tofirst_table mask an array where the data is exactly equal to value, use the numpy.ma.masked_object() method in Python Numpy −
masked_matrix = np.ma.masked_object(firstTable, -1)
sum_of_remaining_numbers = np.ma.array(masked_matrix).sum()
sum_of_remaining_numbers
print(f"Sum of the whole table without crossed out numbers (-1): {sum_of_remaining_numbers}\n")

print(f"The final result is {sum_of_remaining_numbers * decidingNumber}")

The first table to win is 

[[-1 -1 -1 -1 -1]
 [27 29 22 -1 76]
 [58 54 80 -1 -1]
 [-1 24 83 -1 25]
 [21 31 48 39  4]]

and the deciding number was 94

Sum of the whole table including -1 is 611
Sum of the whole table without crossed out numbers (-1): 621

The final result is 58374


In [453]:
import numpy as np

# save tables as matrices
tables = []
matrix = []
for row in setOfTables:
    if row == '':
        if matrix != []: # except the first one
            # write previous
            matrix = np.matrix(matrix)
            tables.append(matrix)
            matrix = []
    else:
        matrix.append([int(i) for i in row.split()])

# tables_to_cross_out = tables
# last_table_data = []

def findLast(draws, tables):
    crossedOutTables = []
    for numberDrawn in draws:
        for table in tables:
            if (table == -1).all(axis=0).any() or (table == -1).all(axis=1).any():
                continue
            else:
                # if the number is in the table, replace the number with -1 (mark it as crossed out)
                if numberDrawn in table:
                    table[table == numberDrawn] = -1
                    # check for BINGO (is there a column or a row which has all values equal to "-1"?)
                    if (table == -1).all(axis=0).any() or (table == -1).all(axis=1).any():
                        crossedOutTables.append([table, numberDrawn])
                        # if len(crossedOutTables)+1 == len(tables):
    return crossedOutTables

# firstTable, decidingNumber = first_table_data[0]

# print(f"The first table to win is \n\n{firstTable}\n\nand the deciding number was {decidingNumber}\n")
# print(f"Sum of the whole table including -1 is {firstTable.sum()}")

# # Tofirst_table mask an array where the data is exactly equal to value, use the numpy.ma.masked_object() method in Python Numpy −
# masked_matrix = np.ma.masked_object(firstTable, -1)
# sum_of_remaining_numbers = np.ma.array(masked_matrix).sum()
# sum_of_remaining_numbers
# print(f"Sum of the whole table without crossed out numbers (-1): {sum_of_remaining_numbers}\n")

# print(f"The final result is {sum_of_remaining_numbers * decidingNumber}")

In [454]:
crossedOutTables = findLast(draws, tables)

In [455]:
len(crossedOutTables), len(tables)

(99, 99)

In [460]:
lastToWinTable, decidingNumber = crossedOutTables[-1]
lastToWinTable, decidingNumber

(matrix([[-1, 99, -1, -1, -1],
         [-1, 30, 10, -1, -1],
         [98, -1, -1, -1, 25],
         [76, -1, 29, -1, -1],
         [-1, -1, -1, -1, -1]]),
 31)

In [461]:
 # To first_table mask an array where the data is exactly equal to value, use the numpy.ma.masked_object() method in Python Numpy −
masked_matrix = np.ma.masked_object(lastToWinTable, -1)
sum_of_remaining_numbers = np.ma.array(masked_matrix).sum()
sum_of_remaining_numbers
print(f"Sum of the whole table without crossed out numbers (-1): {sum_of_remaining_numbers}\n")

print(f"The final result is {sum_of_remaining_numbers * decidingNumber}")

Sum of the whole table without crossed out numbers (-1): 367

The final result is 11377
